version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/golang"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ts"
    schedule:
      interval: "weekly"
