name: Python Build Check

on:
  pull_request:
    paths:
      - python/**
      - .github/workflows/python-build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./python
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Check code
        run: |
          uv run python -m py_compile main.py

      - name: Run tests
        run: |
          if uv run python -c "import pytest" 2>/dev/null; then
            uv run pytest
          else
            echo "pytest not configured, skipping tests"
          fi
