name: Python Build Check

on:
  pull_request:
    paths:
      - python/**
      - .github/workflows/python-build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./python
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Check code
        run: |
          uv run python -m py_compile main.py env.py logger.py

      - name: Run tests
        run: uv run pytest
